grails-app/domain/upclinic/TypeMaladie.groovy
package upclinic

class TypeMaladie {

    String code
    String intitule
    String description

    static constraints = {
        code nullable: false, unique: true, blank: false
        intitule blank: false, nullable: false
        description blank: false, type:'text'
    }
}

grails-app/controllers/upclinic/TypeMaladieController.groovy
package upclinic

import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional

@Transactional(readOnly = true)
class TypeMaladieController {

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond TypeMaladie.list(params), model:[typeMaladieCount: TypeMaladie.count()]
    }

    def show(TypeMaladie typeMaladie) {
        respond typeMaladie
    }

    def create() {
        respond new TypeMaladie(params)
    }

    @Transactional
    def save(TypeMaladie typeMaladie) {
        if (typeMaladie == null) {
            transactionStatus.setRollbackOnly()
            notFound()
            return
        }

        if (typeMaladie.hasErrors()) {
            transactionStatus.setRollbackOnly()
            respond typeMaladie.errors, view:'create'
            return
        }

        typeMaladie.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'typeMaladie.label', default: 'TypeMaladie'), typeMaladie.id])
                redirect typeMaladie
            }
            '*' { respond typeMaladie, [status: CREATED] }
        }
    }

    def edit(TypeMaladie typeMaladie) {
        respond typeMaladie
    }

    @Transactional
    def update(TypeMaladie typeMaladie) {
        if (typeMaladie == null) {
            transactionStatus.setRollbackOnly()
            notFound()
            return
        }

        if (typeMaladie.hasErrors()) {
            transactionStatus.setRollbackOnly()
            respond typeMaladie.errors, view:'edit'
            return
        }

        typeMaladie.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'typeMaladie.label', default: 'TypeMaladie'), typeMaladie.id])
                redirect typeMaladie
            }
            '*'{ respond typeMaladie, [status: OK] }
        }
    }

    @Transactional
    def delete(TypeMaladie typeMaladie) {

        if (typeMaladie == null) {
            transactionStatus.setRollbackOnly()
            notFound()
            return
        }

        typeMaladie.delete flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'typeMaladie.label', default: 'TypeMaladie'), typeMaladie.id])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'typeMaladie.label', default: 'TypeMaladie'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }
}

grails-app/views/typeMaladie/create.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'typeMaladie.label', default: 'TypeMaladie')}" />
        <title><g:message code="default.create.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#create-typeMaladie" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="create-typeMaladie" class="content scaffold-create" role="main">
            <h1><g:message code="default.create.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
            </g:if>
            <g:hasErrors bean="${this.typeMaladie}">
            <ul class="errors" role="alert">
                <g:eachError bean="${this.typeMaladie}" var="error">
                <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
                </g:eachError>
            </ul>
            </g:hasErrors>
            <g:form action="save">
                <fieldset class="form">
                    <f:all bean="typeMaladie"/>
                </fieldset>
                <fieldset class="buttons">
                    <g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
                </fieldset>
            </g:form>
        </div>
    </body>
</html>

grails-app/views/typeMaladie/edit.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'typeMaladie.label', default: 'TypeMaladie')}" />
        <title><g:message code="default.edit.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#edit-typeMaladie" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
                <li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="edit-typeMaladie" class="content scaffold-edit" role="main">
            <h1><g:message code="default.edit.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
            </g:if>
            <g:hasErrors bean="${this.typeMaladie}">
            <ul class="errors" role="alert">
                <g:eachError bean="${this.typeMaladie}" var="error">
                <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
                </g:eachError>
            </ul>
            </g:hasErrors>
            <g:form resource="${this.typeMaladie}" method="PUT">
                <g:hiddenField name="version" value="${this.typeMaladie?.version}" />
                <fieldset class="form">
                    <f:all bean="typeMaladie"/>
                </fieldset>
                <fieldset class="buttons">
                    <input class="save" type="submit" value="${message(code: 'default.button.update.label', default: 'Update')}" />
                </fieldset>
            </g:form>
        </div>
    </body>
</html>

grails-app/views/typeMaladie/index.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'typeMaladie.label', default: 'TypeMaladie')}" />
        <title><g:message code="default.list.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#list-typeMaladie" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                <li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="list-typeMaladie" class="content scaffold-list" role="main">
            <h1><g:message code="default.list.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
                <div class="message" role="status">${flash.message}</div>
            </g:if>
            <f:table collection="${typeMaladieList}" />

            <div class="pagination">
                <g:paginate total="${typeMaladieCount ?: 0}" />
            </div>
        </div>
    </body>
</html>

grails-app/views/typeMaladie/show.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'typeMaladie.label', default: 'TypeMaladie')}" />
        <title><g:message code="default.show.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#show-typeMaladie" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
                <li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="show-typeMaladie" class="content scaffold-show" role="main">
            <h1><g:message code="default.show.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
            </g:if>
            <f:display bean="typeMaladie" />
            <g:form resource="${this.typeMaladie}" method="DELETE">
                <fieldset class="buttons">
                    <g:link class="edit" action="edit" resource="${this.typeMaladie}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
                    <input class="delete" type="submit" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
                </fieldset>
            </g:form>
        </div>
    </body>
</html>