grails-app/domain/upclinic/TypeRendezVous.groovy
package upclinic

class TypeRendezVous {

    String code
    String intitule

    static constraints = {
        code nullable: false, blank: false, unique: true
        intitule inList: ["premier_rv", "rv_apres_consultation"]
    }
}

grails-app/controllers/upclinic/TypeRendezVousController.groovy
package upclinic

import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional

@Transactional(readOnly = true)
class TypeRendezVousController {

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond TypeRendezVous.list(params), model:[typeRendezVousCount: TypeRendezVous.count()]
    }

    def show(TypeRendezVous typeRendezVous) {
        respond typeRendezVous
    }

    def create() {
        respond new TypeRendezVous(params)
    }

    @Transactional
    def save(TypeRendezVous typeRendezVous) {
        if (typeRendezVous == null) {
            transactionStatus.setRollbackOnly()
            notFound()
            return
        }

        if (typeRendezVous.hasErrors()) {
            transactionStatus.setRollbackOnly()
            respond typeRendezVous.errors, view:'create'
            return
        }

        typeRendezVous.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'typeRendezVous.label', default: 'TypeRendezVous'), typeRendezVous.id])
                redirect typeRendezVous
            }
            '*' { respond typeRendezVous, [status: CREATED] }
        }
    }

    def edit(TypeRendezVous typeRendezVous) {
        respond typeRendezVous
    }

    @Transactional
    def update(TypeRendezVous typeRendezVous) {
        if (typeRendezVous == null) {
            transactionStatus.setRollbackOnly()
            notFound()
            return
        }

        if (typeRendezVous.hasErrors()) {
            transactionStatus.setRollbackOnly()
            respond typeRendezVous.errors, view:'edit'
            return
        }

        typeRendezVous.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'typeRendezVous.label', default: 'TypeRendezVous'), typeRendezVous.id])
                redirect typeRendezVous
            }
            '*'{ respond typeRendezVous, [status: OK] }
        }
    }

    @Transactional
    def delete(TypeRendezVous typeRendezVous) {

        if (typeRendezVous == null) {
            transactionStatus.setRollbackOnly()
            notFound()
            return
        }

        typeRendezVous.delete flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'typeRendezVous.label', default: 'TypeRendezVous'), typeRendezVous.id])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'typeRendezVous.label', default: 'TypeRendezVous'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }
}

grails-app/views/typeRendezVous/create.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'typeRendezVous.label', default: 'TypeRendezVous')}" />
        <title><g:message code="default.create.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#create-typeRendezVous" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="create-typeRendezVous" class="content scaffold-create" role="main">
            <h1><g:message code="default.create.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
            </g:if>
            <g:hasErrors bean="${this.typeRendezVous}">
            <ul class="errors" role="alert">
                <g:eachError bean="${this.typeRendezVous}" var="error">
                <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
                </g:eachError>
            </ul>
            </g:hasErrors>
            <g:form action="save">
                <fieldset class="form">
                    <f:all bean="typeRendezVous"/>
                </fieldset>
                <fieldset class="buttons">
                    <g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
                </fieldset>
            </g:form>
        </div>
    </body>
</html>

grails-app/views/typeRendezVous/edit.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'typeRendezVous.label', default: 'TypeRendezVous')}" />
        <title><g:message code="default.edit.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#edit-typeRendezVous" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
                <li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="edit-typeRendezVous" class="content scaffold-edit" role="main">
            <h1><g:message code="default.edit.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
            </g:if>
            <g:hasErrors bean="${this.typeRendezVous}">
            <ul class="errors" role="alert">
                <g:eachError bean="${this.typeRendezVous}" var="error">
                <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
                </g:eachError>
            </ul>
            </g:hasErrors>
            <g:form resource="${this.typeRendezVous}" method="PUT">
                <g:hiddenField name="version" value="${this.typeRendezVous?.version}" />
                <fieldset class="form">
                    <f:all bean="typeRendezVous"/>
                </fieldset>
                <fieldset class="buttons">
                    <input class="save" type="submit" value="${message(code: 'default.button.update.label', default: 'Update')}" />
                </fieldset>
            </g:form>
        </div>
    </body>
</html>

grails-app/views/typeRendezVous/index.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'typeRendezVous.label', default: 'TypeRendezVous')}" />
        <title><g:message code="default.list.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#list-typeRendezVous" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                <li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="list-typeRendezVous" class="content scaffold-list" role="main">
            <h1><g:message code="default.list.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
                <div class="message" role="status">${flash.message}</div>
            </g:if>
            <f:table collection="${typeRendezVousList}" />

            <div class="pagination">
                <g:paginate total="${typeRendezVousCount ?: 0}" />
            </div>
        </div>
    </body>
</html>

grails-app/views/typeRendezVous/show.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'typeRendezVous.label', default: 'TypeRendezVous')}" />
        <title><g:message code="default.show.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#show-typeRendezVous" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
                <li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="show-typeRendezVous" class="content scaffold-show" role="main">
            <h1><g:message code="default.show.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
            </g:if>
            <f:display bean="typeRendezVous" />
            <g:form resource="${this.typeRendezVous}" method="DELETE">
                <fieldset class="buttons">
                    <g:link class="edit" action="edit" resource="${this.typeRendezVous}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
                    <input class="delete" type="submit" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
                </fieldset>
            </g:form>
        </div>
    </body>
</html>